name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: macos-latest
    
    strategy:
      matrix:
        node-version: [16, 18, 20]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install system dependencies
      run: |
        # Ensure Xcode Command Line Tools are available
        xcode-select --install 2>/dev/null || true
        xcode-select --print-path
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run CI tests
      run: npm test
      
    - name: Run basic functionality test
      run: npm run test-basic || echo "Basic test failed (expected in CI without accessibility permissions)"
    
    - name: Build TypeScript example
      run: npm run typescript-compile
      
  build:
    runs-on: macos-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install system dependencies
      run: |
        # Ensure Xcode Command Line Tools are available
        xcode-select --install 2>/dev/null || true
        xcode-select --print-path
    
    - name: Install dependencies
      run: npm ci
    
    - name: Rebuild native module (macOS)
      run: npm run rebuild --workspace=packages/macos
      
    - name: Test native module
      run: npm test --workspace=packages/macos
      
    - name: Verify binary exists
      run: |
        echo "Checking for native binary..."
        find packages/macos -name "*.node" -type f
        ls -la packages/macos/bin/ || echo "No bin directory"